pipeline{
    agent any

    parameters{
        booleanParam(defaultValue: false,description:"Enable Service",name: "myBoolean")
    }
    stages{
        stage("Demo"){
            steps{
                script{
                    if(params.myBoolean==false){
                        currentBuild.result="SUCCESS"
                        return
                    }
                    else{
                                        echo "Boolean Param is set to:${params.myBoolean}"


                    }
                }
            }
        }
    }
}